server:
  port: 8081

spring:
  application:
    name: acp-psp
  jackson:
    property-naming-strategy: SNAKE_CASE
    deserialization:
      fail-on-unknown-properties: false
  datasource:
    url: jdbc:postgresql://localhost:5432/acp
    username: user
    password: password
  jooq:
    sql-dialect: POSTGRES
  jackson:
    property-naming-strategy: SNAKE_CASE

kakaopay:
  base-url: https://kapi.kakao.com
  secret-key: ${KAKAOPAY_SECRET_KEY_DEV}
